name: Deploy eldik_map to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Чекаут кода (для проверки билда локально)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Установка Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
          bun --version

      # 4. Кэширование зависимостей (локально)
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # 5. Установка зависимостей (локально)
      - name: Install dependencies
        run: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install

      # 6. Проверка билда (локально)
      - name: Build frontend
        run: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run build

      # 7. Настройка SSH
      - name: Setup SSH
        if: success()
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "SERVER_HOST: ${{ secrets.SERVER_HOST }}"
          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
            echo "Error: SERVER_HOST is not set"
            exit 1
          fi
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || {
            echo "Error: ssh-keyscan failed"
            exit 1
          }
          chmod 600 ~/.ssh/known_hosts
          echo "SSH setup completed"

      # 8. Деплой на сервер
      - name: Deploy to VM
        if: success()
        run: |
          ssh -v -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_HOST} << 'EOF'
            echo "Connected to VM"
            cd /home/${SERVER_USER}/rsk_taxi/eldik-map || {
              echo "Error: Directory not found. Cloning repository..."
              https://github.com/EmirlanDogdurbaev/eldik-map.git /home/${SERVER_USER}/rsk_taxi/eldik-map
            }
            cd /home/${SERVER_USER}/rsk_taxi/eldik-map
            git pull origin main
            bun install
            bun run build
            sudo rm -rf /var/www/frontend/dist/*
            sudo cp -r dist/* /var/www/frontend/dist/
            sudo chmod -R 755 /var/www/frontend/dist
            sudo chown -R www-data:www-data /var/www/frontend/dist
            sudo systemctl reload nginx
          EOF
